In [1]:
import sys
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
from src.data_processing import build_player_dataset

/Users/devan/Documents/nba-performance-predictor/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
brunson_dataset = build_player_dataset(
    player_id=1628973,
    season="2025-26"
)

brunson_dataset.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,FG3A_LAST_10_AVG,FG3A_SEASON_AVG,FG3A_STD_LAST_5,FG3A_STD_LAST_10,FTA_LAST_GAME,FTA_LAST_5_AVG,FTA_LAST_10_AVG,FTA_SEASON_AVG,FTA_STD_LAST_5,FTA_STD_LAST_10
0,22025,1628973,0022500003,2025-10-22,NYK vs. CLE,W,34,5,18,0.278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22025,1628973,0022500018,2025-10-24,NYK vs. BOS,W,35,10,20,0.500,...,9.0,9.0,NaN,NaN,13.0,13.000000,13.000000,13.000000,NaN,NaN
2,22025,1628973,0022500108,2025-10-26,NYK @ MIA,L,35,14,26,0.538,...,8.0,8.0,1.414214,1.414214,9.0,11.000000,11.000000,11.000000,2.828427,2.828427
3,22025,1628973,0022500125,2025-10-28,NYK @ MIL,L,35,14,25,0.560,...,9.0,9.0,2.000000,2.000000,4.0,8.666667,8.666667,8.666667,4.509250,4.509250
4,22025,1628973,0022500023,2025-10-31,NYK @ CHI,L,35,12,25,0.480,...,8.0,8.0,2.581989,2.581989,9.0,8.750000,8.750000,8.750000,3.685557,3.685557

In [4]:
from nba_api.stats.static import players

players.find_players_by_full_name("Nikola Jokic")

[{'id': 203999,
  'full_name': 'Nikola Jokić',
  'first_name': 'Nikola',
  'last_name': 'Jokić',
  'is_active': True}]

In [5]:
jokic_dataset = build_player_dataset(
    player_id=203999,
    season="2025-26"
)

jokic_dataset.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,FG3A_LAST_10_AVG,FG3A_SEASON_AVG,FG3A_STD_LAST_5,FG3A_STD_LAST_10,FTA_LAST_GAME,FTA_LAST_5_AVG,FTA_LAST_10_AVG,FTA_SEASON_AVG,FTA_STD_LAST_5,FTA_STD_LAST_10
0,22025,203999,0022500006,2025-10-23,DEN @ GSW,L,41,8,23,0.348,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22025,203999,0022500104,2025-10-25,DEN vs. PHX,W,32,5,8,0.625,...,13.000000,13.000000,NaN,NaN,4.0,4.00,4.00,4.00,NaN,NaN
2,22025,203999,0022500008,2025-10-27,DEN @ MIN,W,36,9,10,0.900,...,8.000000,8.000000,7.071068,7.071068,4.0,4.00,4.00,4.00,0.000000,0.000000
3,22025,203999,0022500134,2025-10-29,DEN vs. NOP,W,28,10,15,0.667,...,5.333333,5.333333,6.806859,6.806859,7.0,5.00,5.00,5.00,1.732051,1.732051
4,22025,203999,0022500026,2025-10-31,DEN @ POR,L,37,7,10,0.700,...,4.500000,4.500000,5.802298,5.802298,0.0,3.75,3.75,3.75,2.872281,2.872281

In [6]:
combined = pd.concat([brunson_dataset, jokic_dataset])

combined.head(10)

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,FG3A_LAST_10_AVG,FG3A_SEASON_AVG,FG3A_STD_LAST_5,FG3A_STD_LAST_10,FTA_LAST_GAME,FTA_LAST_5_AVG,FTA_LAST_10_AVG,FTA_SEASON_AVG,FTA_STD_LAST_5,FTA_STD_LAST_10
0,22025,1628973,0022500003,2025-10-22,NYK vs. CLE,W,34,5,18,0.278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22025,1628973,0022500018,2025-10-24,NYK vs. BOS,W,35,10,20,0.500,...,9.000000,9.000000,NaN,NaN,13.0,13.000000,13.000000,13.000000,NaN,NaN
2,22025,1628973,0022500108,2025-10-26,NYK @ MIA,L,35,14,26,0.538,...,8.000000,8.000000,1.414214,1.414214,9.0,11.000000,11.000000,11.000000,2.828427,2.828427
3,22025,1628973,0022500125,2025-10-28,NYK @ MIL,L,35,14,25,0.560,...,9.000000,9.000000,2.000000,2.000000,4.0,8.666667,8.666667,8.666667,4.509250,4.509250
4,22025,1628973,0022500023,2025-10-31,NYK @ CHI,L,35,12,25,0.480,...,8.000000,8.000000,2.581989,2.581989,9.0,8.750000,8.750000,8.750000,3.685557,3.685557
5,22025,1628973,0022500153,2025-11-02,NYK vs. CHI,W,32,10,22,0.455,...,8.000000,8.000000,2.236068,2.236068,5.0,8.000000,8.000000,8.000000,3.605551,3.605551
6,22025,1628973,0022500159,2025-11-03,NYK vs. WAS,W,32,6,17,0.353,...,8.500000,8.500000,2.607681,2.345208,7.0,6.800000,7.833333,7.833333,2.280351,3.250641
7,22025,1628973,0022500175,2025-11-05,NYK vs. MIN,W,33,9,20,0.450,...,8.000000,8.000000,3.000000,2.516611,3.0,5.600000,7.142857,7.142857,2.408319,3.484660
8,22025,1628973,0022500192,2025-11-09,NYK vs. BKN,W,29,6,14,0.429,...,7.875000,7.875000,2.489980,2.356602,2.0,5.200000,6.500000,6.500000,2.863564,3.703280
9,22025,1628973,0022500208,2025-11-11,NYK vs. MEM,W,36,11,19,0.579,...,7.888889,7.888889,2.167948,2.204793,4.0,4.200000,6.222222,6.222222,1.923538,3.562926

Create combined dataset for 2 players (Jalen Brunson and Nikola Jokic)...

In [7]:
test_players = [
    {"name": "Jalen Brunson", "id": 1628973},
    {"name": "Nikola Jokic", "id": 203999},
]

In [8]:
player_datasets = []

for player in test_players:
    print(f"Building dataset for {player['name']}...")

    player_data = build_player_dataset(
        player_id=player["id"],
        season="2025-26"
    )

    player_data["PLAYER_NAME"] = player["name"]

    player_datasets.append(player_data)

    combined_dataset = pd.concat(
    player_datasets,
    ignore_index=True
)
    
combined_dataset[
    [
        "PLAYER_NAME",
        "PLAYER_ID",
        "GAME_DATE",
        "MATCHUP",
        "PTS",
        "REB",
        "AST",
        "PTS_LAST_5_AVG",
    ]
].head(10)

Building dataset for Jalen Brunson...
Building dataset for Nikola Jokic...

,PLAYER_NAME,PLAYER_ID,GAME_DATE,MATCHUP,PTS,REB,AST,PTS_LAST_5_AVG
0,Jalen Brunson,1628973,2025-10-22,NYK vs. CLE,23,4,5,NaN
1,Jalen Brunson,1628973,2025-10-24,NYK vs. BOS,31,3,5,23.000000
2,Jalen Brunson,1628973,2025-10-26,NYK @ MIA,37,5,7,27.000000
3,Jalen Brunson,1628973,2025-10-28,NYK @ MIL,36,4,3,30.333333
4,Jalen Brunson,1628973,2025-10-31,NYK @ CHI,29,2,7,31.750000
5,Jalen Brunson,1628973,2025-11-02,NYK vs. CHI,31,5,3,31.200000
6,Jalen Brunson,1628973,2025-11-03,NYK vs. WAS,16,1,9,32.800000
7,Jalen Brunson,1628973,2025-11-05,NYK vs. MIN,23,7,10,29.800000
8,Jalen Brunson,1628973,2025-11-09,NYK vs. BKN,19,0,7,27.000000
9,Jalen Brunson,1628973,2025-11-11,NYK vs. MEM,32,5,10,23.600000

In [9]:
combined_dataset["PLAYER_NAME"].value_counts()

PLAYER_NAME
Jalen Brunson    74
Nikola Jokic     65
Name: count, dtype: int64

Create full dataset for all players...

In [10]:
from nba_api.stats.static import players

all_players = players.get_players()

active_players = [
    player for player in all_players
    if player["is_active"]
]

len(active_players)

571

In [11]:
import time

player_datasets = []
failed_players = []

for index, player in enumerate(active_players, start=1):
    try:
        print(
            f"{index}/{len(active_players)}: "
            f"Building {player['full_name']}..."
        )

        player_data = build_player_dataset(
            player_id=player["id"],
            season="2025-26"
        )

        if player_data.empty:
            print(f"No games found for {player['full_name']}")
            continue

        player_data["PLAYER_NAME"] = player["full_name"]

        player_datasets.append(player_data)

        time.sleep(0.6)

    except Exception as error:
        print(f"Failed for {player['full_name']}: {error}")

        failed_players.append({
            "PLAYER_NAME": player["full_name"],
            "PLAYER_ID": player["id"],
            "ERROR": str(error)
        })

print(f"\nSuccessfully processed: {len(player_datasets)} players")
print(f"Failed: {len(failed_players)} players")

1/571: Building Precious Achiuwa...
2/571: Building Steven Adams...
3/571: Building Bam Adebayo...
4/571: Building Ochai Agbaji...
5/571: Building Santi Aldama...
6/571: Building Trey Alexander...
7/571: Building Nickeil Alexander-Walker...
8/571: Building Grayson Allen...
9/571: Building Jarrett Allen...
10/571: Building Jose Alvarado...
11/571: Building Kyle Anderson...
12/571: Building Giannis Antetokounmpo...
13/571: Building Cole Anthony...
14/571: Building OG Anunoby...
15/571: Building Taran Armstrong...
No games found for Taran Armstrong
16/571: Building Deni Avdija...
17/571: Building Deandre Ayton...
18/571: Building Marcus Bagley...
No games found for Marcus Bagley
19/571: Building Marvin Bagley III...
20/571: Building Patrick Baldwin Jr....
21/571: Building LaMelo Ball...
22/571: Building Lonzo Ball...
23/571: Building Mo Bamba...
24/571: Building Paolo Banchero...
25/571: Building Desmond Bane...
26/571: Building Dalano Banton...
27/571: Building Dominick Barlow...
28/571: Building Harrison Barnes...
29/571: Building Scottie Barnes...
30/571: Building RJ Barrett...
31/571: Building Charles Bassey...
32/571: Building Emoni Bates...
No games found for Emoni Bates
33/571: Building Jamison Battle...
34/571: Building Nicolas Batum...
35/571: Building Damion Baugh...
No games found for Damion Baugh
36/571: Building Bradley Beal...
37/571: Building Malik Beasley...
No games found for Malik Beasley
38/571: Building MarJon Beauchamp...
39/571: Building Reece Beekman...
No games found for Reece Beekman
40/571: Building Goga Bitadze...
41/571: Building Bismack Biyombo...
42/571: Building Anthony Black...
43/571: Building Bogdan Bogdanović...
44/571: Building Bol Bol...
No games found for Bol Bol
45/571: Building Adem Bona...
46/571: Building Devin Booker...
47/571: Building Brandon Boston...
No games found for Brandon Boston
48/571: Building Chris Boucher...
49/571: Building Jamaree Bouyea...
50/571: Building Tony Bradley...
51/571: Building Malaki Branham...
52/571: Building Christian Braun...
53/571: Building Jalen Bridges...
No games found for Jalen Bridges
54/571: Building Mikal Bridges...
55/571: Building Miles Bridges...
56/571: Building Oshae Brissett...
No games found for Oshae Brissett
57/571: Building Malcolm Brogdon...
No games found for Malcolm Brogdon
58/571: Building Dillon Brooks...
59/571: Building Keion Brooks Jr....
No games found for Keion Brooks Jr.
60/571: Building Bruce Brown...
61/571: Building Jaylen Brown...
62/571: Building Kobe Brown...
63/571: Building Moses Brown...
No games found for Moses Brown
64/571: Building Jalen Brunson...
65/571: Building Thomas Bryant...
66/571: Building Kobe Bufkin...
67/571: Building Alec Burks...
No games found for Alec Burks
68/571: Building Jared Butler...
No games found for Jared Butler
69/571: Building Jimmy Butler III...
70/571: Building Matas Buzelis...
71/571: Building Jamal Cain...
72/571: Building Kentavious Caldwell-Pope...
73/571: Building Toumani Camara...
74/571: Building Clint Capela...
75/571: Building Branden Carlson...
76/571: Building Bub Carrington...
77/571: Building Devin Carter...
78/571: Building Jevon Carter...
79/571: Building Wendell Carter Jr....
80/571: Building D.J. Carton...
No games found for D.J. Carton
81/571: Building Alex Caruso...
82/571: Building Stephon Castle...
83/571: Building Colin Castleton...
84/571: Building Julian Champagnie...
85/571: Building Justin Champagnie...
86/571: Building Ulrich Chomche...
No games found for Ulrich Chomche
87/571: Building Cam Christie...
88/571: Building Max Christie...
89/571: Building Josh Christopher...
No games found for Josh Christopher
90/571: Building Sidy Cissoko...
91/571: Building Jaylen Clark...
92/571: Building Brandon Clarke...
93/571: Building Jordan Clarkson...
94/571: Building Nic Claxton...
95/571: Building Donovan Clingan...
96/571: Building Noah Clowney...
97/571: Building Amir Coffey...
98/571: Building Isaiah Collier...
99/571: Building John Collins...
100/571: Building Yuri Collins...
No games found for Yuri Collins
101/571: Building Zach Collins...
102/571: Building Mike Conley...
103/571: Building Pat Connaughton...
104/571: Building Bilal Coulibaly...
105/571: Building Ricky Council IV...
No games found for Ricky Council IV
106/571: Building Torrey Craig...
No games found for Torrey Craig
107/571: Building Isaiah Crawford...
108/571: Building Jae Crowder...
No games found for Jae Crowder
109/571: Building Cui Cui...
No games found for Cui Cui
110/571: Building Cade Cunningham...
111/571: Building Seth Curry...
112/571: Building Stephen Curry...
113/571: Building Pacôme Dadiet...
114/571: Building Dyson Daniels...
115/571: Building N'Faly Dante...
116/571: Building Anthony Davis...
117/571: Building Johnny Davis...
No games found for Johnny Davis
118/571: Building Terence Davis...
No games found for Terence Davis
119/571: Building JD Davison...
120/571: Building DeMar DeRozan...
121/571: Building RayJ Dennis...
122/571: Building Donte DiVincenzo...
123/571: Building Moussa Diabaté...
124/571: Building Gradey Dick...
125/571: Building Ousmane Dieng...
126/571: Building Rob Dillingham...
127/571: Building Spencer Dinwiddie...
No games found for Spencer Dinwiddie
128/571: Building Luka Dončić...
129/571: Building Luguentz Dort...
130/571: Building Ayo Dosunmu...
131/571: Building Jeff Dowtin Jr....
No games found for Jeff Dowtin Jr.
132/571: Building PJ Dozier...
No games found for PJ Dozier
133/571: Building Andre Drummond...
134/571: Building Chris Duarte...
No games found for Chris Duarte
135/571: Building Alex Ducas...
No games found for Alex Ducas
136/571: Building David Duke Jr....
No games found for David Duke Jr.
137/571: Building Kris Dunn...
138/571: Building Ryan Dunn...
139/571: Building Kevin Durant...
140/571: Building Jalen Duren...
141/571: Building Tari Eason...
142/571: Building Zach Edey...
143/571: Building Anthony Edwards...
144/571: Building Jesse Edwards...
No games found for Jesse Edwards
145/571: Building Justin Edwards...
146/571: Building Kessler Edwards...
No games found for Kessler Edwards
147/571: Building Keon Ellis...
148/571: Building Joel Embiid...
149/571: Building Tyson Etienne...
150/571: Building Drew Eubanks...
151/571: Building Tosan Evbuomwan...
152/571: Building Danté Exum...
No games found for Danté Exum
153/571: Building Bruno Fernando...
No games found for Bruno Fernando
154/571: Building Kyle Filipowski...
155/571: Building Dorian Finney-Smith...
156/571: Building Adam Flagler...
No games found for Adam Flagler
157/571: Building Trentyn Flowers...
158/571: Building Malachi Flynn...
No games found for Malachi Flynn
159/571: Building Simone Fontecchio...
160/571: Building De'Aaron Fox...
161/571: Building Enrique Freeman...
162/571: Building Markelle Fultz...
163/571: Building Johnny Furphy...
164/571: Building Daniel Gafford...
165/571: Building Darius Garland...
166/571: Building Marcus Garrett...
No games found for Marcus Garrett
167/571: Building Luka Garza...
168/571: Building Keyonte George...
169/571: Building Kyshawn George...
170/571: Building Paul George...
171/571: Building Taj Gibson...
172/571: Building Josh Giddey...
173/571: Building Shai Gilgeous-Alexander...
174/571: Building Anthony Gill...
175/571: Building Collin Gillespie...
176/571: Building Rudy Gobert...
177/571: Building Jordan Goodwin...
178/571: Building Aaron Gordon...
179/571: Building Eric Gordon...
180/571: Building Jazian Gortman...
No games found for Jazian Gortman
181/571: Building Jerami Grant...
182/571: Building AJ Green...
183/571: Building Draymond Green...
184/571: Building Jalen Green...
185/571: Building Javonte Green...
186/571: Building Jeff Green...
187/571: Building Josh Green...
188/571: Building Quentin Grimes...
189/571: Building Mouhamed Gueye...
190/571: Building Rui Hachimura...
191/571: Building Tyrese Haliburton...
No games found for Tyrese Haliburton
192/571: Building PJ Hall...
193/571: Building Tim Hardaway Jr....
194/571: Building James Harden...
195/571: Building Jaden Hardy...
196/571: Building Elijah Harkless...
197/571: Building Ron Harper Jr....
198/571: Building Gary Harris...
199/571: Building Tobias Harris...
200/571: Building Josh Hart...
201/571: Building Isaiah Hartenstein...
202/571: Building Sam Hauser...
203/571: Building Jordan Hawkins...
204/571: Building Jaxson Hayes...
205/571: Building Killian Hayes...
206/571: Building Scoot Henderson...
207/571: Building Taylor Hendricks...
208/571: Building Tyler Herro...
209/571: Building Buddy Hield...
210/571: Building Haywood Highsmith...
211/571: Building Aaron Holiday...
212/571: Building Jrue Holiday...
213/571: Building Ronald Holland II...
214/571: Building Richaun Holmes...
No games found for Richaun Holmes
215/571: Building Chet Holmgren...
216/571: Building Jalen Hood-Schifino...
No games found for Jalen Hood-Schifino
217/571: Building Al Horford...
218/571: Building Talen Horton-Tucker...
No games found for Talen Horton-Tucker
219/571: Building Caleb Houstan...
220/571: Building Jett Howard...
221/571: Building Kevin Huerter...
222/571: Building Jay Huff...
223/571: Building Ariel Hukporti...
224/571: Building De'Andre Hunter...
225/571: Building Bones Hyland...
226/571: Building Oso Ighodaro...
227/571: Building Joe Ingles...
228/571: Building Brandon Ingram...
229/571: Building Harrison Ingram...
230/571: Building Kyrie Irving...
No games found for Kyrie Irving
231/571: Building Jonathan Isaac...
232/571: Building Jaden Ivey...
233/571: Building GG Jackson...
234/571: Building Isaiah Jackson...
235/571: Building Quenton Jackson...
236/571: Building Reggie Jackson...
No games found for Reggie Jackson
237/571: Building Andre Jackson Jr....
238/571: Building Jaren Jackson Jr....
239/571: Building Trayce Jackson-Davis...
240/571: Building Bronny James...
241/571: Building LeBron James...
242/571: Building Jaime Jaquez Jr....
243/571: Building DaQuan Jeffries...
244/571: Building Trey Jemison III...
245/571: Building Daniss Jenkins...
246/571: Building Ty Jerome...
247/571: Building Isaiah Joe...
248/571: Building AJ Johnson...
249/571: Building Cameron Johnson...
250/571: Building Jalen Johnson...
251/571: Building James Johnson...
No games found for James Johnson
252/571: Building Keldon Johnson...
253/571: Building Keon Johnson...
No games found for Keon Johnson
254/571: Building Keshad Johnson...
255/571: Building Nikola Jokić...
256/571: Building Colby Jones...
257/571: Building Dillon Jones...
258/571: Building Herbert Jones...
259/571: Building Isaac Jones...
260/571: Building Kai Jones...
No games found for Kai Jones
261/571: Building Mason Jones...
No games found for Mason Jones
262/571: Building Spencer Jones...
263/571: Building Tre Jones...
264/571: Building Tyus Jones...
265/571: Building Derrick Jones Jr....
266/571: Building DeAndre Jordan...
267/571: Building Cory Joseph...
No games found for Cory Joseph
268/571: Building Nikola Jović...
269/571: Building Johnny Juzang...
270/571: Building Yuki Kawamura...
271/571: Building Kylor Kelley...
No games found for Kylor Kelley
272/571: Building Luke Kennard...
273/571: Building Walker Kessler...
274/571: Building Braxton Key...
No games found for Braxton Key
275/571: Building Corey Kispert...
276/571: Building Maxi Kleber...
277/571: Building Bobi Klintman...
278/571: Building Dalton Knecht...
279/571: Building Kevin Knox II...
No games found for Kevin Knox II
280/571: Building Tyler Kolek...
281/571: Building Christian Koloko...
282/571: Building John Konchar...
283/571: Building Luke Kornet...
284/571: Building Vít Krejčí...
285/571: Building Jonathan Kuminga...
286/571: Building Kyle Kuzma...
287/571: Building Jake LaRavia...
288/571: Building Zach LaVine...
289/571: Building Skal Labissiere...
290/571: Building Jock Landale...
291/571: Building Pelle Larsson...
292/571: Building A.J. Lawson...
293/571: Building Caris LeVert...
294/571: Building Damion Lee...
No games found for Damion Lee
295/571: Building Alex Len...
No games found for Alex Len
296/571: Building Kawhi Leonard...
297/571: Building Malevy Leons...
298/571: Building Maxwell Lewis...
Failed for Maxwell Lewis: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
299/571: Building E.J. Liddell...
300/571: Building Damian Lillard...
No games found for Damian Lillard
301/571: Building Dereck Lively II...
302/571: Building Chris Livingston...
303/571: Building Kevon Looney...
304/571: Building Brook Lopez...
305/571: Building Kevin Love...
306/571: Building Kyle Lowry...
307/571: Building Seth Lundy...
No games found for Seth Lundy
308/571: Building Trey Lyles...
No games found for Trey Lyles
309/571: Building Sandro Mamukelashvili...
310/571: Building Terance Mann...
311/571: Building Tre Mann...
312/571: Building Lauri Markkanen...
313/571: Building Naji Marshall...
314/571: Building Caleb Martin...
315/571: Building Cody Martin...
316/571: Building Jaylen Martin...
No games found for Jaylen Martin
317/571: Building KJ Martin...
No games found for KJ Martin
318/571: Building Tyrese Martin...
319/571: Building Garrison Mathews...
320/571: Building Bennedict Mathurin...
321/571: Building Karlo Matković...
322/571: Building Tyrese Maxey...
323/571: Building Miles McBride...
324/571: Building Jared McCain...
325/571: Building Mac McClung...
326/571: Building CJ McCollum...
327/571: Building T.J. McConnell...
328/571: Building Kevin McCullar Jr....
329/571: Building Jaden McDaniels...
330/571: Building Jalen McDaniels...
No games found for Jalen McDaniels
331/571: Building Doug McDermott...
332/571: Building Bryce McGowens...
333/571: Building Jordan McLaughlin...
334/571: Building Jack McVeigh...
No games found for Jack McVeigh
335/571: Building De'Anthony Melton...
336/571: Building Sam Merrill...
337/571: Building Vasilije Micic...
No games found for Vasilije Micic
338/571: Building Khris Middleton...
339/571: Building Brandon Miller...
340/571: Building Emanuel Miller...
341/571: Building Jordan Miller...
342/571: Building Leonard Miller...
343/571: Building Patty Mills...
No games found for Patty Mills
344/571: Building Shake Milton...
No games found for Shake Milton
345/571: Building Justin Minaya...
No games found for Justin Minaya
346/571: Building Riley Minix...
347/571: Building Josh Minott...
348/571: Building Yves Missi...
349/571: Building Ajay Mitchell...
350/571: Building Davion Mitchell...
351/571: Building Donovan Mitchell...
352/571: Building Evan Mobley...
353/571: Building Isaiah Mobley...
No games found for Isaiah Mobley
354/571: Building Jonathan Mogbo...
355/571: Building Malik Monk...
356/571: Building Moses Moody...
357/571: Building Taze Moore...
No games found for Taze Moore
358/571: Building Wendell Moore Jr....
359/571: Building Ja Morant...
360/571: Building Markieff Morris...
No games found for Markieff Morris
361/571: Building Monté Morris...
362/571: Building Trey Murphy III...
363/571: Building Dejounte Murray...
364/571: Building Jamal Murray...
365/571: Building Keegan Murray...
366/571: Building Kris Murray...
367/571: Building Svi Mykhailiuk...
368/571: Building Pete Nance...
369/571: Building Larry Nance Jr....
370/571: Building Andrew Nembhard...
371/571: Building Aaron Nesmith...
372/571: Building Tristen Newton...
373/571: Building Georges Niang...
No games found for Georges Niang
374/571: Building Daishen Nix...
No games found for Daishen Nix
375/571: Building Zeke Nnaji...
376/571: Building Miles Norris...
No games found for Miles Norris
377/571: Building Jaylen Nowell...
No games found for Jaylen Nowell
378/571: Building Jusuf Nurkić...
379/571: Building Royce O'Neale...
380/571: Building Jahlil Okafor...
No games found for Jahlil Okafor
381/571: Building Chuma Okeke...
No games found for Chuma Okeke
382/571: Building Josh Okogie...
383/571: Building Onyeka Okongwu...
384/571: Building Isaac Okoro...
385/571: Building Quincy Olivari...
No games found for Quincy Olivari
386/571: Building Kelly Olynyk...
387/571: Building Kelly Oubre Jr....
388/571: Building Chris Paul...
389/571: Building Cameron Payne...
390/571: Building Elfrid Payton...
No games found for Elfrid Payton
391/571: Building Gary Payton II...
392/571: Building Drew Peterson...
393/571: Building Julian Phillips...
394/571: Building Jalen Pickett...
395/571: Building Scotty Pippen Jr....
396/571: Building Daeqwon Plowden...
397/571: Building Mason Plumlee...
398/571: Building Brandin Podziemski...
399/571: Building Jakob Poeltl...
400/571: Building Jordan Poole...
401/571: Building Craig Porter Jr....
402/571: Building Kevin Porter Jr....
403/571: Building Michael Porter Jr....
404/571: Building Bobby Portis...
405/571: Building Kristaps Porziņģis...
406/571: Building Quinten Post...
407/571: Building Micah Potter...
408/571: Building Dwight Powell...
409/571: Building Norman Powell...
410/571: Building Taurean Prince...
411/571: Building Payton Pritchard...
412/571: Building Olivier-Maxence Prosper...
413/571: Building Zyon Pullin...
414/571: Building Trevelin Queen...
No games found for Trevelin Queen
415/571: Building Neemias Queta...
416/571: Building Immanuel Quickley...
417/571: Building Lester Quinones...
No games found for Lester Quinones
418/571: Building Julius Randle...
419/571: Building Duop Reath...
420/571: Building Austin Reaves...
421/571: Building Cam Reddish...
No games found for Cam Reddish
422/571: Building Paul Reed...
423/571: Building Alex Reese...
No games found for Alex Reese
424/571: Building Antonio Reeves...
425/571: Building Naz Reid...
426/571: Building Jared Rhoden...
No games found for Jared Rhoden
427/571: Building Nick Richards...
428/571: Building Josh Richardson...
No games found for Josh Richardson
429/571: Building Zaccharie Risacher...
430/571: Building Liam Robbins...
No games found for Liam Robbins
431/571: Building Duncan Robinson...
432/571: Building Mitchell Robinson...
433/571: Building Orlando Robinson...
434/571: Building Jeremiah Robinson-Earl...
435/571: Building David Roddy...
436/571: Building Ryan Rollins...
437/571: Building Jackson Rowe...
No games found for Jackson Rowe
438/571: Building Terry Rozier...
No games found for Terry Rozier
439/571: Building Rayan Rupert...
440/571: Building D'Angelo Russell...
441/571: Building Matt Ryan...
No games found for Matt Ryan
442/571: Building Domantas Sabonis...
443/571: Building Tidjane Salaün...
444/571: Building Adama Sanogo...
No games found for Adama Sanogo
445/571: Building Gui Santos...
446/571: Building Alex Sarr...
447/571: Building Marcus Sasser...
448/571: Building Baylor Scheierman...
449/571: Building Dennis Schröder...
450/571: Building Alperen Sengun...
451/571: Building Brice Sensabaugh...
452/571: Building Collin Sexton...
453/571: Building Landry Shamet...
454/571: Building Terrence Shannon Jr....
455/571: Building Day'Ron Sharpe...
456/571: Building Shaedon Sharpe...
457/571: Building Jamal Shead...
458/571: Building Ben Sheppard...
459/571: Building Reed Sheppard...
460/571: Building Pascal Siakam...
461/571: Building Ben Simmons...
No games found for Ben Simmons
462/571: Building Anfernee Simons...
463/571: Building KJ Simpson...
464/571: Building Jaylen Sims...
No games found for Jaylen Sims
465/571: Building Jericho Sims...
466/571: Building Marcus Smart...
467/571: Building Dru Smith...
468/571: Building Jalen Smith...
469/571: Building Tolu Smith...
470/571: Building Tyler Smith...
471/571: Building Jabari Smith Jr....
472/571: Building Nick Smith Jr....
473/571: Building Jeremy Sochan...
474/571: Building Cam Spencer...
475/571: Building Pat Spencer...
476/571: Building Jaden Springer...
No games found for Jaden Springer
477/571: Building Isaiah Stevens...
478/571: Building Lamar Stevens...
No games found for Lamar Stevens
479/571: Building Isaiah Stewart...
480/571: Building Julian Strawther...
481/571: Building Max Strus...
482/571: Building Jalen Suggs...
483/571: Building Cole Swider...
No games found for Cole Swider
484/571: Building Jae'Sean Tate...

In [12]:
print("Dataset shape:", combined_dataset.shape)
print("Players included:", combined_dataset["PLAYER_NAME"].nunique())
print("Date range:", combined_dataset["GAME_DATE"].min(), "to", combined_dataset["GAME_DATE"].max())
print("Duplicate rows:", combined_dataset.duplicated(
    subset=["PLAYER_ID", "Game_ID"]
).sum())

Dataset shape: (139, 75)
Players included: 2
Date range: 2025-10-22 00:00:00 to 2026-04-12 00:00:00
Duplicate rows: 0

In [13]:
full_dataset = pd.concat(
    player_datasets,
    ignore_index=True
)

In [14]:
print("Dataset shape:", full_dataset.shape)
print("Players included:", full_dataset["PLAYER_NAME"].nunique())
print(
    "Date range:",
    full_dataset["GAME_DATE"].min(),
    "to",
    full_dataset["GAME_DATE"].max()
)
print(
    "Duplicate rows:",
    full_dataset.duplicated(
        subset=["Player_ID", "Game_ID"]
    ).sum()
)

Dataset shape: (22926, 75)
Players included: 464
Date range: 2025-10-21 00:00:00 to 2026-04-12 00:00:00
Duplicate rows: 0

In [18]:
feature_columns = [
    "IS_HOME",
    "REST_DAYS",
    "GAMES_PLAYED",

    "PTS_LAST_GAME",
    "PTS_LAST_5_AVG",
    "PTS_LAST_10_AVG",
    "PTS_SEASON_AVG",
    "PTS_STD_LAST_5",
    "PTS_STD_LAST_10",

    "REB_LAST_GAME",
    "REB_LAST_5_AVG",
    "REB_LAST_10_AVG",
    "REB_SEASON_AVG",
    "REB_STD_LAST_5",
    "REB_STD_LAST_10",

    "AST_LAST_GAME",
    "AST_LAST_5_AVG",
    "AST_LAST_10_AVG",
    "AST_SEASON_AVG",
    "AST_STD_LAST_5",
    "AST_STD_LAST_10",

    "MIN_LAST_GAME",
    "MIN_LAST_5_AVG",
    "MIN_LAST_10_AVG",
    "MIN_SEASON_AVG",
    "MIN_STD_LAST_5",
    "MIN_STD_LAST_10",

    "FGA_LAST_GAME",
    "FGA_LAST_5_AVG",
    "FGA_LAST_10_AVG",
    "FGA_SEASON_AVG",
    "FGA_STD_LAST_5",
    "FGA_STD_LAST_10",

    "FG3A_LAST_GAME",
    "FG3A_LAST_5_AVG",
    "FG3A_LAST_10_AVG",
    "FG3A_SEASON_AVG",
    "FG3A_STD_LAST_5",
    "FG3A_STD_LAST_10",

    "FTA_LAST_GAME",
    "FTA_LAST_5_AVG",
    "FTA_LAST_10_AVG",
    "FTA_SEASON_AVG",
    "FTA_STD_LAST_5",
    "FTA_STD_LAST_10",
]

In [19]:
print("Dataset shape:", full_dataset.shape)
print("Players included:", full_dataset["PLAYER_NAME"].nunique())
print(
    "Date range:",
    full_dataset["GAME_DATE"].min(),
    "to",
    full_dataset["GAME_DATE"].max()
)
print(
    "Duplicate rows:",
    full_dataset.duplicated(
        subset=["Player_ID", "Game_ID"]
    ).sum()
)

print(full_dataset[feature_columns].isna().sum())

Dataset shape: (22926, 75)
Players included: 464
Date range: 2025-10-21 00:00:00 to 2026-04-12 00:00:00
Duplicate rows: 0
IS_HOME               0
REST_DAYS           464
GAMES_PLAYED          0
PTS_LAST_GAME       464
PTS_LAST_5_AVG      464
PTS_LAST_10_AVG     464
PTS_SEASON_AVG      464
PTS_STD_LAST_5      926
PTS_STD_LAST_10     926
REB_LAST_GAME       464
REB_LAST_5_AVG      464
REB_LAST_10_AVG     464
REB_SEASON_AVG      464
REB_STD_LAST_5      926
REB_STD_LAST_10     926
AST_LAST_GAME       464
AST_LAST_5_AVG      464
AST_LAST_10_AVG     464
AST_SEASON_AVG      464
AST_STD_LAST_5      926
AST_STD_LAST_10     926
MIN_LAST_GAME       464
MIN_LAST_5_AVG      464
MIN_LAST_10_AVG     464
MIN_SEASON_AVG      464
MIN_STD_LAST_5      926
MIN_STD_LAST_10     926
FGA_LAST_GAME       464
FGA_LAST_5_AVG      464
FGA_LAST_10_AVG     464
FGA_SEASON_AVG      464
FGA_STD_LAST_5      926
FGA_STD_LAST_10     926
FG3A_LAST_GAME      464
FG3A_LAST_5_AVG     464
FG3A_LAST_10_AVG    464
FG3A_SEASON_AVG     464
FG3A_STD_LAST_5     926
FG3A_STD_LAST_10    926
FTA_LAST_GAME       464
FTA_LAST_5_AVG      464
FTA_LAST_10_AVG     464
FTA_SEASON_AVG      464
FTA_STD_LAST_5      926
FTA_STD_LAST_10     926
dtype: int64

In [17]:
full_dataset.to_csv(
    "../data/processed/full_dataset.csv",
    index=False
)

In [20]:
model_dataset_v2 = full_dataset.dropna(
    subset=feature_columns
).copy()

In [21]:
print("V2 model dataset shape:", model_dataset_v2.shape)

print(
    "Total missing feature values:",
    model_dataset_v2[feature_columns].isna().sum().sum()
)

print(
    "Players included:",
    model_dataset_v2["PLAYER_NAME"].nunique()
)

V2 model dataset shape: (22000, 75)
Total missing feature values: 0
Players included: 459

In [22]:
model_dataset_v2.to_csv(
    "../data/processed/model_dataset_v2.csv",
    index=False
)